### ISSUE TITLE
Fontconfig error on windows (app 187)

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shinycoreci#118]
Appears related to https://github.com/rstudio/shiny/issues/3626

```
###
Running tests for app: 187-navbar-collapse

Loading required package: shiny
Loading required package: testthat
✔ | F W S  OK | Context

⠏ |         0 | shinyjster                                                      shinyjster - starting app: 187-navbar-collapse
Running java -jar "D:/a/_temp/Library/shinyjster/selenium/selenium.jar" \
  chrome 550x700 "http://127.0.0.1:6711/?shinyjster=1" 120 --headless
pxjava - Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 21516
pxjava - Only local connections are allowed.
pxjava - Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
pxjava - ChromeDriver was started successfully.
pxjava - Jun 13, 2022 8:31:25 AM org.openqa.selenium.remote.ProtocolHandshake createSession
pxjava - INFO: Detected dialect: W3C
Fontconfig error: Cannot load default config file
shinyjster - Browser window has been closed. Stopping Shiny Application now.
shinyjster - stopping app: 187-navbar-collapse
```

**Comment by cpsievert** [comment]
FWIW, I can't seem to repro this on R4.2.1 with Windows 11 (via parallels VM on an M1 mac)

**Comment by MadhulikaTanuboddi** [comment]
> cc @MadhulikaTanuboddi try repro-ing by installing R 4.2 on Windows and running app 187

@cpsievert : Just want to let you know, I was able to repro the font config error with 187 (after installing Cairo from CRAN and Shiny from github).  Probably odd: I was able to run app 187 fine and the plot displayed as expected. However, I have noticed the error `Fontconfig error: Cannot load default config file` in the R console. Seems like thats the same behavior the user reported too from https://github.com/rstudio/shiny/issues/3626#issue-1220095686 (somehow, I was under the impression that plots wont render properly).

Please keep me posted on this one. I know you were suggesting to use `ragg` instead of `cairo`

**Comment by cpsievert** [comment]
For posterity, `Fontconfig error: Cannot load default config file` wasn't actually causing these failures, but it has probably been causing widespread font rendering degradation on Windows with R 4.2.

Since that Fontconfig issue is Cairo's issue to fix, and we've been thinking already of switching from Cairo to ragg, we're likely going to do that here https://github.com/rstudio/shiny/pull/3654

(We may see lots of small changes to plot screenshots as a result)
